### ISSUE TITLE
dotOpacity? 

### ISSUE THREAD

**Issue by Aduffy** [moonwave99/fretboard.js#12]
Is there a dotOpacity option in config? 

What I am trying to do is display all of the notes in a pentatonic scale on the full fretboard with the dots shown at .5 opacity. Then have  buttons that used fretboard.style() to set the opacity of all notes in box 1, box 2 etc.. 

![image](https://user-images.githubusercontent.com/265857/100527574-916bb380-3188-11eb-976a-3120146fba30.png)

**Comment by moonwave99** [comment]
This is exactly one of the use cases I had in mind when I started the project ^^

I tweaked the dot class generator a bit in v0.1.9 [11293ad] in order to have a finer styling control - [see example](https://codepen.io/moonwave99/pen/ZEpYrpz).

The idea is to flatten al positions in a single array, by keeping track of the boxes they belonged to.

Adding a `boxes: number[]` key to the existing dots array is enough:

```js
[
  ...
  {  string: 6, fret: 5, boxes: [1] }, 
  {  string: 6, fret: 8, boxes: [1] }, 
  {  string: 5, fret: 5, boxes: [1, 2] }, 
  {  string: 5, fret: 7, boxes: [2] }, 
  ...
]
```

The rendered SVG will be:

```svg
<g class="dots">
  <g class="dot dot-boxes-1">
    <circle>...</circle>
    <text>...</text>
  </g>
  <g class="dot dot-boxes-1">
    <circle>...</circle>
    <text>...</text>
  </g>
  ...
  <g class="dot dot-boxes-1 dot-boxes-2">
    <circle>...</circle>
    <text>...</text>
  </g>
  ...
  <g class="dot dot-boxes-2">
    <circle>...</circle>
    <text>...</text>
  </g>
</g>
```

You can select `.dot-boxes-$box` now, toggle your own classes and style accordingly in CSS.

**Comment by Aduffy** [comment]
Friggin brilliant! THANK YOU. The example code is really helpful!

**Comment by Aduffy** [comment]
On a similar note I was also thinking on being able to toggle between showing note and interval names.. if the dot contained an additional text element with the interval name in it and a class of .dot-interval, then i could also use CSS to hide the .dot-text and show dot-interval instead..

**Comment by moonwave99** [comment]
Like in the [homepage](https://moonwave99.github.io/fretboard.js/) example? [[source](https://github.com/moonwave99/fretboard.js/blob/master/site/scripts/home.js)]

You can use `style({ text })` for that:

```js
button.addEventListener('click', ({ currentTarget }) => {
    switch (currentTarget.dataset.action) {
        case 'show-notes':
        fretboard.style({
            text: ({ note }) => note,
            fill: colors.defaultFill
        });
        break;
        case 'show-notes-with-octave':
        fretboard.style({
            text: ({ noteWithOctave }) => noteWithOctave,
            fontSize: 10,
            fill: ({ octave }) => colors.octaves[octave]
        });
        break;
        case 'show-intervals':
        fretboard.style({
            text: ({ interval }) => interval,
            fill: colors.defaultFill
        });
        break;
        case 'highlight-triad':
        fretboard.style({
            filter: ({ degree }) => [1, 3, 5].indexOf(degree) > -1,
            stroke: 'red'
        });
        break;
        default:
        fretboard.style({
            text: () => null,
            fill: colors.defaultFill,
            stroke: 'black'
        });
        break;
    }
});
```

**Comment by Aduffy** [comment]
LOL.. ya kinda Exactly like the home page example... funny I have not been back to your home page since I first found you... .
