### ISSUE TITLE
noteWithOctive class names for Sharps # 

### ISSUE THREAD

**Issue by Aduffy** [moonwave99/fretboard.js#20]
there is a bit of a problem with the notWithOctive class names when dealing with sharps 

"#" does not play well with class names, although it can be used as a selector by escaping it  such as F\# 

Im doing some integrating of fretbboard.js with ABCjs.js (inspired by your playback example) and they way they handle sharps there is to use the b version of the name ..  Gb3 instead of F#3

Perhaps both flavors of name could be used on those notes ? dot-noteWithOctave-F#3 and dot-noteWithOctave-Gb3 ?

**Comment by moonwave99** [comment]
Ah, the enharmonic notes problem!

In the iteration I am working, all dots will include the [`chroma`][chroma] property, i.e. the 0-12 value they have in equal temperament regardless of their name.

So boh F# and Gb will have 6 as chroma. To get the chroma value of a note you can use `chroma` from the `@tonaljs/note` package (as I am doing in the library).

Nevertheless it makes sense to have an attribute value sanitiser just in case.

[chroma]: https://en.wikipedia.org/wiki/Chroma_feature

**Comment by Aduffy** [comment]
Sounds like a perfect solution ! Thanks

**Comment by moonwave99** [comment]
In version 0.2 the classes are added as:

- `C#` -> `dot-note-C-sharp`;
- `C##` -> `dot-note-C-double-sharp`;
- `Bb` -> `dot-note-B-flat`;
- `Bbb` -> `dot-note-B-double-flat`.

Hope it helps!

**Comment by Aduffy** [comment]
Cool Is this in addition to the chroma based class name?

**Comment by Aduffy** [comment]
YES!  ^^  / Answers self
