### ISSUE TITLE
renderScale function inclued class name for "inBox" on dot

### ISSUE THREAD

**Issue by Aduffy** [moonwave99/fretboard.js#22]
I see that I can style the dots with the built in style() function using he inBox: true/false. But could we also add a class name to the dot indicating it is inBox?  

What i would like to archive is to have the full scale presented at .5 opacity, and the box at 1.  But I would also like to have the dots go to full opacity on hover.

**Comment by moonwave99** [comment]
It is already the case (`.dot-in-box`), [see examples](https://moonwave99.github.io/fretboard.js/examples-systems.html).
