### ISSUE TITLE
Three note per string minor scale box position appears to be off

### ISSUE THREAD

**Issue by caged** [moonwave99/fretboard.js#29]
:wave: 

In comparing fretboard.js to a couple of other sites,  it seems like fretboard's TNPS system is using a different numerical index for the box shapes.   As an example, here is an F minor,  at position 1 across a few different implementations:

### [guitar-chords.org.uk](https://www.guitar-chords.org.uk/guitarscales/f-natural-minor-scale.html)

Positions aren't labeled here, but they are in numerical order from left to right.

![fminorscale-3nps](https://user-images.githubusercontent.com/25/103974093-00441100-5126-11eb-9b79-10efee274a69.gif)

### [Fretastic](https://fretastic.com/guitar)

<img width="1049" alt="Screen Shot 2021-01-07 at 8 22 51 PM" src="https://user-images.githubusercontent.com/25/103974159-2b2e6500-5126-11eb-91c0-54bfbad7e6c8.png">

### fretboard.js

<img width="1213" alt="Screen Shot 2021-01-07 at 8 25 22 PM" src="https://user-images.githubusercontent.com/25/103974370-882a1b00-5126-11eb-85e7-78c4f215b55f.png">

But if we swap to position 6, we see the same notes as the other two sites:

<img width="1222" alt="Screen Shot 2021-01-07 at 8 44 39 PM" src="https://user-images.githubusercontent.com/25/103975538-3cc53c00-5129-11eb-9643-2110a34ffa10.png">

I don't know if there are any hard and fast rules when it comes to this,  but it might be worth having consistency with existing implementations.  Cheers!

**Comment by moonwave99** [comment]
The inconsistency here depends on the fact that the library is providing 1-7 boxes for the **major** scale - so the natural minor scale is its 6th box.

One could make alias indexes for certain scales, so the 1st box of the minor scale (6th mode) is what is displayed in the other sites. I am thinking about a consistent API for that, that does not depend on the scale type.

Honestly I don't think numbering boxes to provide much information, it is all about knowing which notes are you playing - but I see your point ^^

**Comment by caged** [comment]
> Honestly I don't think numbering boxes to provide much information, it is all about knowing which notes are you playing - but I see your point ^^

Likewise on your point.  Feel free to close this if you ultimately wish to keep it the way it is.
