### ISSUE TITLE
Feature Request: renderScale full fretboard with all box shape class names 

### ISSUE THREAD

**Issue by Aduffy** [moonwave99/fretboard.js#30]
Any chance you would consider adding the ability to render a scale with all notes having a class name for all boxes it belonged to?

**Comment by moonwave99** [comment]
Hey Alex!

I think the feature is too specific to be included in the library itself.

It shouldn't be too complicated to achieve it by calling `FretboardSystem.getScale()` for the same scale with two different boxes, and by adding the classes manually. Utilities from `lodash` may help!

**Comment by Aduffy** [comment]
Ya i had started to do just that.. then thought maybe check with you in case you'd add it in.. All good. as you say easy enough to do.
