### ISSUE TITLE
renderChord broken in latest version? (maybe last version too)

### ISSUE THREAD

**Issue by GastroGeek** [moonwave99/fretboard.js#46]
Hi,

Firstly - awesome tool! I've been having some fun using it!

I spent hours thinking my code was broken, only to realise that if you go here:

https://moonwave99.github.io/fretboard.js/examples-chords.html

You will notice the barr-C chord renders _fine_... i.e. with dots against fret 5.

However, if you render the same chord using 'master/HEAD' (0.2.7?)... it just shows the bar but the notes are not rendered against fret 5. Guessing the offset is not being calculated properly or something (since any callbacks using {dots} param only passes dots on fret 3) - didn't dig in too deep as my needs are met by using 0.2.5 but figured I would flag it

If you could fix this, _please_, that would be awesome! 🙏

**Comment by moonwave99** [comment]
You are right!

<img width="1284" alt="Screenshot 2022-05-11 at 17 37 42" src="https://user-images.githubusercontent.com/380184/167890404-691079c4-8890-4127-9334-763cd282b4d9.png">

I think it was introduced in the last commit on master - will check asap and find a fix!

Meanwhile, [things are stable w/ 0.2.7](https://codepen.io/diego-spiced/pen/jOZrQWV).

**Comment by GastroGeek** [comment]
@moonwave99 that seems a _little_ better, but suspect there is still something else going on? (unless I am misunderstanding the `crop` property?)

https://codepen.io/gastrogeek/pen/KKQMYJE?editors=1010
(hope this works for you - hover over the notes...)

Notice how the `fret` and `note` reported back from the 'mousemove' event are incorrect? I assume it should be conditionally changing the fret/note offset based on the `crop` property? and thus how much _cropping_ has occured? (i.e. how many frets offset are there before that first note?)

**Comment by moonwave99** [comment]
Should be fixed now @GastroGeek !

The offset was not taken into account while cropping.
