### ISSUE TITLE
Is there a browser based version for non NPM users? 

### ISSUE THREAD

**Issue by Aduffy** [moonwave99/fretboard.js#6]
Is there a browser based version for non NPM users? 
I have tried using UNPKG and jsdelivr but both get error "Cant find variable Fretboard" 

`
<figure id="fretboard"></figure>
	
	<script src="https://cdn.jsdelivr.net/npm/@moonwave99/fretboard.js"></script>

	<script>
		const fretboard = new Fretboard({
			  el: '#fretboard'
			});
		const box = CAGED({
			  mode: 'major',
			  root: 'C3',
			  box: 'C'
			});
		fretboard.render(box);
	</script>`

**Comment by moonwave99** [comment]
Yes there is, [the `UMD` dist file](https://cdn.jsdelivr.net/npm/@moonwave99/fretboard.js/dist/fretboard.umd.js)!

The global is called `fretboard`:

```js
const { Fretboard } = fretboard;
const f = new Fretboard({
  el: '#fretboard',
});

f.render();
```

[See working example](https://codepen.io/moonwave99/pen/ExyqYQR)

**Comment by Aduffy** [comment]
Thanks Diago I had tired that with out luck. Got it now using the lowercase fretboard. 

Also it seems that there are no events when used this way ? 

f.on('mousemove', position => f.render([position])); get an error (also in your codepen) "TypeError: f.on is not a function" . 

Is there another way to access the events ? 

It would be awesome if you could include the the code used for your examples on those pages as well, so people could see how you pulled off each one. 

Cheers!

**Comment by moonwave99** [comment]
I checked and it works if you include the [latest version](https://cdn.jsdelivr.net/npm/@moonwave99/fretboard.js@0.1.8/dist/fretboard.umd.min.js), thank you for pointing out!

I attached the code in the [same example as above](https://codepen.io/moonwave99/pen/ExyqYQR).

I will include code in the examples themselves asap ^^ for now please resort to [the docs](https://moonwave99.github.io/fretboard.js/documentation-fretboard.html#events).
