### ISSUE TITLE
add or remove note

### ISSUE THREAD

**Issue by Aduffy** [moonwave99/fretboard.js#8]
Is there a (built in)  method of adding or removing a note from the fretboard with out having to completely re-render the fretboard ?

**Comment by moonwave99** [comment]
Not at the moment, but you can hide a position (without removing it) with the [`style`](https://moonwave99.github.io/fretboard.js/documentation-fretboard.html#style) method:

```js
const fretboard = new Fretboard({...});

fretboard.render([...]);

// toggle flag on button click for instance
let showRoots = true;

fretboard.style({
    filter: ({ interval }) => interval === '1P',
    opacity: +showRoots
});
```

[See pen](https://codepen.io/moonwave99/pen/PoGYvQg)
